### ISSUE TITLE
Feature request: bidirectional communication

### ISSUE THREAD

**Issue by W1M0R** [frafra/postgresql2websocket#38]
Is it possible for the browser to send a message to the channel, and to have a function in the database handle that message?

**Comment by frafra** [comment]
Uh, that would be interesting :-) I am curious about what you would like to accomplish with that.

Thanks for the suggestion!

**Comment by W1M0R** [comment]
It would allow the browser to send data in real-time over an already established websocket to the database. The registered database function will process the data, and then it can either reject the data, or insert it into the relevant database table, or manage a cron job, or respond with a new payload, etc.

This will offer an alternative to REST-based read-write access to the database, without having to create your own microservice backend.

Consider the example of a phone application that would like to transmit GPS location in real-time to the database. Over an established websocket channel it would be more performant than having to POST on an HTTP endpoint.

Perhaps another benefit is being able to construct an artificial "ping" and to send it over the websocket to request specific information from the database. 

Maybe there is a cron job in the database that sends data over the websocket every 1 minute, but the admin console would like to change that interval to every 30 seconds. It can send a message over the websocket which the database will receive and interpret as a command, and the database would then respond accordingly.

These are just a few examples of how such functionality might be used.

**Comment by frafra** [comment]
You are right. I like that. I am going to implement postgresql-functions-over-websocket :-)

**Comment by frafra** [comment]
Basic support added it in 1994196.
